### ISSUE TITLE
Class files in org.csstudio.utility.pvmanager.{vtype,sys} plugins

### ISSUE THREAD

**Issue by richardfearn** [ControlSystemStudio/maven-osgi-bundles#10]
Not sure if this is intentional, but these two plugins include class files that have been committed into the repository.

I haven't looked in detail but I think that for the other pvmanager plugins, JARs are downloaded and repackaged. So it might be that the class files in vtype and sys are actually unnecessary.

**Comment by berryma4** [comment]
Yes, they can be removed.
